# Generated by Django 5.2.12 on 2026-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='chapters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='index',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
